[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/shots"
  to = "https://script.google.com/macros/s/AKfycbx3Ve1GOp90lyHgugxSZ7uSVMJaq6a4bXqCd-Imn0O5MikCV1010kjBLlIBQAHTfGFf/exec"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200!